#!/bin/bash
#
# This script runs omnet-intermittent-opportunistic-routing simulations 
# for running parallel simulations on a multicore machine

EXEC_DIR=$(pwd)

if [ "$1" = "" ]; then
  RUN_NUMBER=0
else 
  RUN_NUMBER=$1
fi

cd ~/omnetpp6/

source setenv

cd ~/omnetpp6_ws/inet/

source setenv

cd $EXEC_DIR

OUT=$EXEC_DIR/../src

BATCH_SIZE=$(( ${SLURM_CPUS_ON_NODE}*5/4 ))
EXEC="opp_runall -j2 -b${BATCH_SIZE} -e GNUmakefile $OUT/omnet-intermittent-opportunistic-routing -u Cmdenv -f test.ini -c IntermittentORPLImmediateDownwardsTest"

INET_NEDFOLDERS=$(cat $INET_ROOT/.nedfolders | sed "s|^|$INET_ROOT/|" | tr '\n' ':')
if [ ! "$INET_NEDFOLDERS" = "" ]; then
  INET_OMNETPP_OPTIONS="-n $INET_NEDFOLDERS $INET_OMNETPP_OPTIONS"
fi

INET_NEDEXCLUSIONS=$(cat $INET_ROOT/.nedexclusions | tr '\n' ':')
if [ ! "$INET_NEDEXCLUSIONS" = "" ]; then
  INET_OMNETPP_OPTIONS="-x $INET_NEDEXCLUSIONS $INET_OMNETPP_OPTIONS"
fi

SRC_NEDFOLDERS="-n ../src -n ../simulations"

echo "Starting multinode simulations on ${SLURM_JOB_NUM_NODES} nodes"
echo "Current node cpu alloc is $SLURM_CPUS_ON_NODE"

$EXEC $INET_OMNETPP_OPTIONS $SRC_NEDFOLDERS -l $INET_ROOT/src/INET -r $RUN_NUMBER
sed -i 's/CMD = /CMD =  srun -n1 opp_runall -j\\\${SLURM_CPUS_ON_NODE} /' GNUmakefile
make VERBOSE=1 -j$SLURM_JOB_NODES

