#!/bin/bash
#SBATCH --ntasks=80
#SBATCH --time=00:04:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=el7g15@soton.ac.uk

RUN_IDS="0..96"
echo $RUN_IDS

export OMP_NUM_THREADS=1

module load gcc/11
module load gnumake/4.2
module load python
whereis libguile-2.0.so.22
module list

cd $HOME/omnetpp6_ws/omnet-intermittent-opportunistic-routing/simulations
../runpar $RUN_IDS 
