#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=00:04:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=el7g15@soton.ac.uk

#SBATCH --array=0-3
BASE=$((${SLURM_ARRAY_TASK_ID}*6))
RUN_IDS="$BASE..$(($BASE+5))"
echo $RUN_IDS
cd $HOME/omnetpp6_ws/omnet-intermittent-opportunistic-routing/simulations
../runpar $RUN_IDS 
